### ISSUE TITLE
Unit Testing has changed in ASP.NET Core

### ISSUE THREAD

**Issue by Programazing** [Content-Core/content-core#1]
It seems we can't test the way we're used to in .Net Core. You can't add a reference to the main project in the test project. We'll need to look into this and see what the current best practise is.

**Comment by MaherJendoubi** [comment]
@Programazing Here is how Microsoft ASP.NET Core team uses unit testing https://github.com/aspnet/Mvc/tree/dev/test/Microsoft.AspNetCore.Mvc.Core.Test

**Comment by MaherJendoubi** [comment]
@Programazing this is a good resource https://xunit.github.io/docs/getting-started-dotnet-core.html
